image: python:latest

before_script:
  - python --version 
  - python -m pip install ".[docs,test]"

test:
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  script:
    - python -m pytest
    - black --check .
    - isort --check .
  only:
    refs:
      - merge_requests

# Run verification tests
Verification:
  script:
    - export TF_CPP_MIN_LOG_LEVEL=1
    - python -m pip install astropy
    - python -m pytest scripts/astropy_verification.py
  when: manual
  only:
    - merge_requests

pages:
  script:
    - sphinx-apidoc -Mfeo docs/source mycosmo
    - sphinx-build docs/source docs/build
    - mv docs/build public/
  artifacts:
    paths:
      - public
  only:
      - main
